const types = {
    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    GET_ALL_POSTS: "GET_ALL_POSTS",
    GET_ALL_SPECIALITIES: "GET_ALL_SPECIALITIES",
    GET_ALL_COURSES: "GET_ALL_COURSES",
    GET_ALL_TEACHERS: "GET_ALL_TEACHERS",
    GET_POST: "GET_POST",
    GET_SPECIALITY: "GET_SPECIALITY",
    GET_COURSE: "GET_COURSE",
    GET_CLASS: "GET_CLASS",
    CREATE_POST: "CREATE_POST"
}

export default types
